# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_matched_pairs_cpp <- function(strata, y, X, treatment = NULL) {
    .Call(`_bclogit_process_matched_pairs_cpp`, strata, y, X, treatment)
}
